increased number of concepts to 447
concepticon/concepticon-data pull request #1151
Opened 2021-11-10 12:40 UTC by StasReichert

# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

...

2021-11-10 14:09 UTC, LinguList requested changes
We would need at least a short definition per entry here, could you provide this, @StasReichert ?

2021-11-15 14:06 UTC, LinguList requested changes
Please add the concept list as well in this stage, otherwise, the tests will fail.

2021-11-15 14:06 UTC, LinguList commented on concepticondata/conceptlists.tsv
> +Gerardi-2021-447	Gerardi, Fabrício and Aragon, Carolina and Reichert Stanislav	2021		447	basic	English,Portuguese	Tupían languages	https://calc.hypotheses.org/2988	Gerardi2021c		This list extends pre
Entries should end in full stop. Page ranges from the PDF can be added.

2021-11-15 14:06 UTC, LinguList commented on concepticondata/references/references.bib
> +@Article{Gerardi2021c,
Volume and Number and Page range are given in the PDF we prepared of your blog post.

2021-12-01 16:50 UTC, StasReichert commented
Sorry for the prolonged wait. I have included the requested changes but I may have missed one thing you mentioned. Which list did you want me to include so that the test do not fail? I am a bit at the loss here as all the tsv files seem to be there.

2021-12-02 08:04 UTC, LinguList approved these changes

2021-12-02 08:15 UTC, merged

2021-12-02 09:22 UTC, LinguList commented
All fine now, as far as I can see. I meant the Gerardi-2021 list