Added Nimuendaju1958 (from Araujo 1996, issue #610).
concepticon/concepticon-data pull request #1153
Opened 2021-12-05 22:40 UTC by marthuis

# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

...

2021-12-06 07:06 UTC, chrzyki commented
Hi @marthuis, thanks for preparing this list! Before we start the review process I'd kindly ask you to take care of the auto formattings that seem to have been applied to the different files you edited:

- capitalization and auto formatting in conceptlists.tsv
- large bulk of indentation (?) changes in references.bib

Thanks!

2021-12-06 08:03 UTC, LinguList reviewed
Thanks a lot. Can I ask you to correct one crucial point already? Obviously, you use a spreadsheet editor, as you corrected the DATES in the conceptlists.tsv, which again were introduced by somebody unnoticed, as they do not make any sense, since cases like 07. Nov in line 173 should be page ranges. And they were apparently overwritten in the past! E.g. 173 Nagaraja-2013-200 is on page 7-11, so you see, what I think what happened was that the spreadsheet interprets page ranges as dates and converts them as such. So we really need to revert those page ranges back. 

Or @chrzyki, what do you think: we go back in the history until we restore the version without this automatic modification and then make sure to correct this in a separate issue? 

In any case, the upper-casing in the spreadsheet would have to be corrected or reverted (see the DIFF for conceptlists.tsv).

2021-12-06 08:06 UTC, chrzyki commented
> Thanks a lot. Can I ask you to correct one crucial point already? Obviously, you use a spreadsheet editor, as you corrected the DATES in the conceptlists.tsv, which again were introduced by somebody unnoticed, as they do not make any sense, since cases like 07. Nov in line 173 should be page ranges. And they were apparently overwritten in the past! E.g. 173 Nagaraja-2013-200 is on page 7-11, so you see, what I think what happened was that the spreadsheet interprets page ranges as dates and converts them as such. So we really need to revert those page ranges back.
> 
> Or @chrzyki, what do you think: we go back in the history until we restore the version without this automatic modification and then make sure to correct this in a separate issue?
> 
> In any case, the upper-casing in the spreadsheet would have to be corrected or reverted (see the DIFF for conceptlists.tsv).

Yes, I agree, we should handle that in a separate issue/PR. Also a good practice for @marthuis to see how merge conflicts can be resolved.

2021-12-07 11:18 UTC, LinguList commented on concepticondata/conceptlists.tsv
> +Maciejewski-2016-100	Maciejewski, Greg and Klepousniotou, Ekaterini	2016		100	ratings	English	English	" http://osf.io/7k3eh/"	Maciejewski2016		The list comprises relative meaning frequencies for 100
There are some cases of `"` which should not be there in the file, you can see this from the DIFF here. Originally : 
```
http://osf.io/7k3eh/
```

now

```
" http://osf.io/7k3eh/"
```
This should be reverted.

2021-12-07 11:19 UTC, LinguList reviewed
Okay, now we have problems with the quotes `"` as I mentioned in one comment. They should not be used here.

2022-02-14 15:13 UTC, LinguList requested changes
So @marthuis if we proceed with this list now. What you can do is:

Actively download the most recent conceptlists.tsv from the github (open conceptlists.tsv in raw, then save). Introduce only that one line for hte concept list you add here, in the end, and do so in a text file, to not auto-format (until you have control over preventing auto-formating). 

Put it into your repository instead of the previous conceptlists.tsv

Then, you do a git pull to get the most recent version, and if there are no warnings, push again to this branch here.

We'll then make sure to review the mappings.

2022-02-21 15:18 UTC, LinguList commented
Let me know if running tests works on your side, as this means we can further proceed with sharing some of the basic linking data here.

2022-02-23 13:17 UTC, marthuis commented
@LinguList This is clear, the tab error should be fixed now, thanks!

2022-02-23 13:21 UTC, LinguList commented
Well, I am afraid you have re-introduced the autoformatting now, which I fixed some time ago.

2022-02-23 13:37 UTC, marthuis commented
@LinguList I'm on it. Also to be sure, as you can see the Nimuendaju-1958-298 file from this PR does not contain a GLOSS column, but was validated. Should I add it before committing to the new PR?

2022-02-23 13:55 UTC, LinguList commented
You need either an ENGLISH column or a GLOSS column. I will check with 
the new PR or your update.

2022-02-24 16:39 UTC, closed without merging