Updated Chen-2019-61
concepticon/concepticon-data pull request #1228
Opened 2022-09-15 06:34 UTC by mathildavz

Following the google sheet, I have mapped some unlinked concepts. 
Some comments: 

- 1771 TASTELESS & 2157 FINE OR THIN occur twice in the list (tasteless: -12, -23; fine: -16, -42)
- Chen-2019-61-30: STRONG appears to refer to taste, so maybe this should be unmapped again

2022-09-21 09:39 UTC, LinguList requested changes
See my comments, I hope they are clear, and thanks for this PR!

2022-09-21 09:39 UTC, LinguList commented on concepticondata/conceptlists/Chen-2019-61.tsv
> +Chen-2019-61-23	23	清淡	清淡	qing1-dan4	not salty/of mild taste	insipid	V_G	4.814814815	1.62962963	1.444444444	3.185185185	0.333333333	Gustatory	0.392853699	1771	TASTELESS
I'd leave this "tasteless" and unmap the other "tasteless" above.

2022-09-21 09:39 UTC, LinguList commented on concepticondata/conceptlists/Chen-2019-61.tsv
> +Chen-2019-61-30	30	濃烈	浓烈	nong2-lie4	of intense taste-scorching	strong	G_H	4.481481481	2.592592593	1.555555556	4.407407407	0.555555556	Gustatory	0.288826213	785	STRONG
Refers to taste, I'd unlink it, as strong refers to force in concepticon.

2022-09-21 09:39 UTC, LinguList commented on concepticondata/conceptlists/Chen-2019-61.tsv
> +Chen-2019-61-45	45	苦楚	苦楚	ku3-chu3	bitter-painful	suffering	G_H	1.740740741	2.740740741	2.222222222	0.851851852	0.407407407	Visual	0.293019576	1783	PAIN
ratehr unmap, not a word commonly used to refer to PAIN.

2022-09-22 10:53 UTC, LinguList approved these changes

2022-09-22 13:49 UTC, AnnikaTjuka approved these changes
Thanks, @mathildavz ! Feel free to merge.

2022-10-04 08:11 UTC, merged