Updated DiezAlamo-2018-750
concepticon/concepticon-data pull request #1233
Opened 2022-09-27 08:22 UTC by mathildavz

I've mapped some unlinked concepts in DiezAlamo-2018-750.

2022-09-27 08:23 UTC, mathildavz commented
I will add some comments today in the afternoon.

2022-09-27 15:54 UTC, mathildavz commented
- DiezAlamo-2018-750-30 - ELEPHANT TRUNK: I think the piece of furniture is meant, I would unmap
- DiezAlamo-2018-750-78 - HAWK: the toy kite is meant, I would unmap
- DiezAlamo-2018-750-83 - CROWN OF HEAD: it seems to refer to money, I would unmap
- DiezAlamo-2018-750-127 - LEAF (LEAFLIKE OBJECT): the word refers to reading according to the comments
- DiezAlamo-2018-750-173 - PALM TREE: a unit for distance seems to be meant, I would unmapped
- DiezAlamo-2018-750-196 - RADIO: chemical element is meant, I would unmap
- DiezAlamo-2018-750-529 - POT: they mean a carpenter's tool, I would unmap

2022-09-28 06:47 UTC, AnnikaTjuka commented
Another list with Spanish glosses. @MuffinLinwist Could you also review the list? I'll send you some screenshots on how to make a review with multiple comments via Mattermost.

2022-09-28 11:10 UTC, LinguList commented
Yes, thanks in advance for quickly checking, @MuffinLinwist, I can then check after your comments.

2022-09-28 13:34 UTC, MuffinLinwist commented
Yes, @AnnikaTjuka, @mathildavz, and @LinguList. I am starting to work on this.

2022-09-28 15:03 UTC, MuffinLinwist reviewed
@AnnikaTjuka, @mathildavz, and @LinguList my review is done.

2022-09-29 09:39 UTC, AnnikaTjuka commented on concepticondata/conceptlists/DiezAlamo-2018-750.tsv
> +DiezAlamo-2018-750-76	76	COJÍN	cushion	PILLOW	1044	5.3030303030303	2.28	7.29166666666667	1.76923076923077	1.41935483870968	2.5625	2.84	6.01694915254237	6.022	6.429	Muebles (An article of furniture)
In this case, I'd unmap.

2022-09-29 09:44 UTC, AnnikaTjuka commented on concepticondata/conceptlists/DiezAlamo-2018-750.tsv
> +DiezAlamo-2018-750-117	117	FUSIL	rifle	GUN	1566	3.875	3.56	4.58333333333333	7.88461538461539	6.67741935483871	1.5625	2.8	4.8135593220339	5.909	5.836	Armas (A weapon)
There are some 'rifle' glosses in other lists that are currently unmapped. @mathildavz Could you open an issue where we discuss adding a new concept RIFLE?

2022-09-29 09:45 UTC, AnnikaTjuka commented on concepticondata/conceptlists/DiezAlamo-2018-750.tsv
> +DiezAlamo-2018-750-127	127	HOJA	leaf	LEAF (LEAFLIKE OBJECT)	2250	3.72727272727273	3.68	7.66666666666667	2.15384615384615	1.48387096774194	3.25	2.96	6.2	5.261	6.232	Material de lectura (A type of read
Yes, the concept LEAF (LEAFLIKE OBJECT) excludes the "plant meaning". In other lists, we mapped 'hoja' to LEAF so I'd suggest to do the same here.

2022-09-29 09:48 UTC, AnnikaTjuka commented on concepticondata/conceptlists/DiezAlamo-2018-750.tsv
> +DiezAlamo-2018-750-173	173	PALMA	palm	PALM TREE	1181	3.24242424242424	4.08	5.125	3.26923076923077	3.45161290322581	2.9375	2.92	5.1864406779661	4.05	6.417	Unidades de longitud (A unit of distance)
The category `Unidades de longitud (A unit of distance)` indicates that the concept 1183 PALM OF HAND is meant.

2022-09-29 09:55 UTC, AnnikaTjuka commented on concepticondata/conceptlists/DiezAlamo-2018-750.tsv
>  DiezAlamo-2018-750-693	693	COMERCIO	shop	SHOP	746	4.29166666666667	2.34615384615385	1.34615384615385	1.58333333333333	4.75	2.29166666666667	3.25	3.23728813559322	5.14	5.323
The authors state that the list represents concrete concepts. So I wouldn't map to a verb concept.

2022-09-29 09:58 UTC, AnnikaTjuka commented
Many thanks for the review, @MuffinLinwist! I left a few comments, but I mostly agree with your suggestions.

2022-09-30 10:36 UTC, LinguList commented
I just quickly checked the discussion here. If you need me to have a thorougher look, this may have to wait until next week. Otherwise, I agree and approve with the discussion and the then final version.

2022-09-30 10:36 UTC, LinguList approved these changes

2022-10-04 07:53 UTC, mathildavz commented
I've implemented the changes. Does someone want to check again, or should I just merge?

2022-10-04 08:37 UTC, AnnikaTjuka commented
I'll have a look at the changes today.

2022-10-04 10:24 UTC, AnnikaTjuka requested changes
There are still a few unresolved issues. I added comments accordingly.

2022-10-04 10:24 UTC, AnnikaTjuka commented on concepticondata/conceptlists/DiezAlamo-2018-750.tsv
> +DiezAlamo-2018-750-127	127	HOJA	leaf	LEAF (LEAFLIKE OBJECT)	2250	3.72727272727273	3.68	7.66666666666667	2.15384615384615	1.48387096774194	3.25	2.96	6.2	5.261	6.232	Material de lectura (A type of read
This needs to be mapped to LEAF.

2022-10-04 10:24 UTC, AnnikaTjuka commented on concepticondata/conceptlists/DiezAlamo-2018-750.tsv
> +DiezAlamo-2018-750-117	117	FUSIL	rifle	GUN	1566	3.875	3.56	4.58333333333333	7.88461538461539	6.67741935483871	1.5625	2.8	4.8135593220339	5.909	5.836	Armas (A weapon)
I'd unmap this for now.

2022-10-04 10:24 UTC, AnnikaTjuka commented on concepticondata/conceptlists/DiezAlamo-2018-750.tsv
> +DiezAlamo-2018-750-551	551	RIFLE	rifle	GUN	1566	3.04166666666667	3.72	5.79166666666667	7.4	6.625	1.76	2.83333333333333				Armas (A weapon)
I'd unmap it for now.

2022-10-05 11:46 UTC, LinguList commented
Yes, @AnnikaTjuka, hoja should be just mapped to LEAF.

2022-10-06 07:23 UTC, mathildavz commented
Sorry for missing those! I have implemented the comments now, and it should be ready to merge. @AnnikaTjuka

2022-10-06 08:16 UTC, AnnikaTjuka approved these changes
Great! Now everything looks good and you can merge, @mathildavz.

2022-10-07 08:14 UTC, merged