Add Swadesh-1961-100
concepticon/concepticon-data pull request #1266
Opened 2022-10-27 08:41 UTC by mathildavz

# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

...

2022-10-27 08:44 UTC, mathildavz commented
I want to add the concept list Swadesh-1961-100. The output of `concepticon test` is the following:
```
(new-env) mathildavanzantwijk@AirvonMathilda concepticon-data % concepticon --repos=/Users/mathildavanzantwijk/CALC/concepticon-data test
INFO    concepticon/concepticon-data at /Users/mathildavanzantwijk/CALC/concepticon-data
testing 411 concept lists
INFO    all integrity tests passed: OK
```

The question that remains for me is how to acknowledge Evgenia Korovina, who linked the list?

2022-10-27 08:50 UTC, AnnikaTjuka commented
Regarding the question of the contributor: You need to edit this file: /concepticon-data/CONTRIBUTORS.md

Under the header "People", you'll find a description of the abbreviations used.
```
Many people helped us in many ways in assembling the data. They pointed us to missing lists (M), provided scans (S), digitized data (D), typed off and corrected concept lists (C), provided translations (T), linked concept lists (L), provided corrections of concept definitions and concept linkings (P), or gave important advice (A), and (G) contributed new data via the GitHub-Workflow.
```

Based on the discussion in the Issue, can you reconstruct which of these categories fit, @mathildavz?

2022-10-27 13:32 UTC, LinguList requested changes
Please see my minor suggestions.

2022-10-27 13:32 UTC, LinguList commented on concepticondata/conceptlists.tsv
> +Swadesh-1961-100	Swadesh, Morris	1961		100	basic	Spanish	Mexican Languages		Swadesh1961		This concept list is Swadesh's translation of the "Swadesh-100" to Spanish.	242-266
Please re-write `"Swadesh-100"` to the internal reference as `[Swadesh list of 100 items](:ref:Swadesh-1955-100)`.

2022-10-27 13:32 UTC, LinguList commented on concepticondata/conceptlists/Swadesh-1961-100.tsv
> +ID	NUMBER	SPANISH	ENGLISH	CONCEPTICON_ID	CONCEPTICON_GLOSS
instead of ENGLISH, you should write GLOSS, as this is an external translation not attested in teh original source.

2022-10-27 13:32 UTC, LinguList commented on concepticondata/references/references.bib
> +  Volume                              = {6},
Here we miss the NUMBER: 
```
Number     = {13},
```

2022-10-28 06:01 UTC, mathildavz commented
> Regarding the question of the contributor: You need to edit this file: /concepticon-data/CONTRIBUTORS.md
> 
> Under the header "People", you'll find a description of the abbreviations used.
> 
> ```
> Many people helped us in many ways in assembling the data. They pointed us to missing lists (M), provided scans (S), digitized data (D), typed off and corrected concept lists (C), provided translations (T), linked concept lists (L), provided corrections of concept definitions and concept linkings (P), or gave important advice (A), and (G) contributed new data via the GitHub-Workflow.
> ```
> 
> Based on the discussion in the Issue, can you reconstruct which of these categories fit, @mathildavz?

I would argue for M, D and L. @AnnikaTjuka

2022-10-28 06:05 UTC, AnnikaTjuka commented
> I would argue for M, D and L. @AnnikaTjuka

Sounds good. Then you can edit the CONTRIBUTORS.md file accordingly.

2022-10-28 06:37 UTC, AnnikaTjuka reviewed
I have just one small comment regarding the mapping.

2022-10-28 06:37 UTC, AnnikaTjuka commented on concepticondata/conceptlists/Swadesh-1961-100.tsv
> +Swadesh-1961-100-76	76	lluvia	rain	2108	RAINING OR RAIN
_lluvia_ is usually mapped to RAIN (PRECIPITATION), except for [Heggarty-2005-150-81](https://concepticon.clld.org/values/Heggarty-2005-150-81). I'd follow the mapping of the majority of the lists and remap this one.

2022-10-28 06:52 UTC, mathildavz commented
I've implemented your comment @AnnikaTjuka. Is this ready to be merged now or is there anything else?

2022-10-28 07:08 UTC, AnnikaTjuka approved these changes
Looks good from my side, but @LinguList requested changes, so he needs to approve too.

2022-11-02 15:25 UTC, LinguList approved these changes
The conflicst which we have now in the data must be resolved. Let me know if you want me to do this now, or if you want to try it yourself. It is actually not difficult, if there are not many of the conflicts in the data.

2022-11-02 15:33 UTC, AnnikaTjuka commented
Thanks for approving the PR, @LinguList! Since @mathildavz will be in the office tomorrow, I thought the two of us could do it together to practice.

2022-11-03 10:06 UTC, AnnikaTjuka commented
We fixed all conflicts. I'll merge now.

2022-11-03 10:06 UTC, merged