Update Luangthongkum-2019-341.tsv
concepticon/concepticon-data pull request #1295
Opened 2023-02-09 14:52 UTC by MuffinLinwist

# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [x] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

...

This is the new mapping for Luangthongkumkaren concept list.

2023-02-09 15:31 UTC, Tarotis requested changes
I was quite surprised to see that the list was already there, but then again, the mappings did need improvement, so thanks a lot for fixing this, there are some really good and important catches.

There is one general trend I am observing: If we have two rather different meanings present, like "ashes" and "fireplace", or "eye", "face", the entry should not be mapped. In other cases, it's important to pay attention to the details in concepticon: Are there two similar concepts, of which one is not used actively in concepticon (launder vs wash clothes)? What is the transitivity of the action?

I did not go through all changes, but especially the first pattern is quite frequent. It would be great if you could go through the changes again and check for the three cases I just described. I expect that there are a lot less changes necessary than have actually been implemented right now.

2023-02-09 15:31 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-30	30	boil (v.)	2492	BOIL (SOMETHING)
Its not specified whether it is the transitive or intransitive meaning, so we should stay with the broader mapping BOIL

2023-02-09 15:31 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-36	36	broken, split, separate	588	BROKEN
I'd leave both unmapped

2023-02-09 15:31 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-60	60	close (one’s eyes)	2211	CLOSE THE EYES
[CLOSE THE EYES](https://concepticon.clld.org/parameters/2211) seems to be discontinued, so the mapping should remain

2023-02-09 15:31 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-68	68	cross (v.)
"cross" is usually mapped to TRANSIT, so this should stay

2023-02-09 15:31 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-77	77	deaf	458	DEAF PERSON
not remap

2023-02-09 15:31 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-79	79	deer (barking~)
not remap, barking deers seem to be a thing

2023-02-09 15:31 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-92	92	dry(v.)	2015	MAKE DRY
transitivity unclear, not map

2023-02-09 15:31 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-337	337	yam, potato	410	YAM
different meanings, rather not remap

2023-02-09 15:31 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-336	336	wrong, mistake, error	1390	WRONG
different meanings, rather not remap

2023-02-09 15:31 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-322	322	wash (clothes)	3434	WASH (CLOTHES)
WASH (CLOTHES) is not used, so we'd rather stay with LAUNDER

2023-02-09 15:31 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-311	311	trunk (of a tree), firewood	344	TREE TRUNK
different meanings, rather no mapping

2023-02-09 15:31 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-283	283	string, rope	362	STRING
different meanings, rather no mapping

2023-02-09 15:31 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-136	136	hair (head~)	1040	HAIR
head is specified, mapping should remain

2023-02-09 17:02 UTC, LinguList commented
I agree with @tarotis, thanks for checking this. If these suggestions are accounted for, you can merge.

2023-02-13 11:08 UTC, MuffinLinwist commented
@Tarotis, I have implemented the changes and you requested me. Also, I identified some other entries with the first pattern you mentioned so I modified them as well. Now, the concept list should be optimal.

2023-02-13 14:46 UTC, LinguList commented
@Tarotis, can I ask you to merge etc. if you find all is done well?

2023-02-14 07:43 UTC, Tarotis requested changes
Thanks for the update @MuffinLinwist . I added now a full review. Once these changes are in, we can merge.

2023-02-14 07:43 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-86	86	disappear, lost	485	DISAPPEAR
"disappear" and "lost" are two different meanings, would not map

2023-02-14 07:43 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
>  Luangthongkum-2019-341-92	92	dry(v.)
Could be mapped to DRY UP

2023-02-14 07:43 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-94	94	dung, excrement	2057	DUNG (ANIMAL FAECES)
would not map, seems to refer to both faeces (human) and dung (animals)

2023-02-14 07:43 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-108	108	fall down	2894	TUMBLE (FALL DOWN)
most previous cases of "fall down" are mapped to FALL, so I would stick with this

2023-02-14 07:43 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-163	163	lemur (flying~), flying squirrel	3271	FLYING SQUIRREL
would not map, flying lemurs and flying squirrels are different species

2023-02-14 07:43 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-172	172	live, stay	363	DWELL (LIVE, RESIDE)
difficult to interpret "stay" in this context, would probably keep unmapped

2023-02-14 07:43 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-175	175	long (of length), tall, high	1203	LONG
should stay LONG OR TALL, otherwise we lose the meanings of "tall" and "high"

2023-02-14 07:43 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-197	197	nail	2128	CLAW OR NAIL
Are we sure there is some CLAW meaning to it? Otherwise, it could be FINGERNAL OR TOENAIL, which is what "nail" is usually mapped to

2023-02-14 07:43 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-209	209	ox, bull, cow
could be mapped to CATTLE I think

2023-02-14 07:43 UTC, Tarotis commented on concepticondata/conceptlists/Luangthongkum-2019-341.tsv
> +Luangthongkum-2019-341-256	256	short, low	1645	SHORT
"short" and "low" are different meanings, would not map to one of them

2023-02-15 12:51 UTC, MuffinLinwist commented
@Tarotis, thanks for the full review. Now all the changes are implemented and the checks have been passed.

2023-02-15 12:58 UTC, Tarotis commented
Thanks, this looks good now, thank you.

2023-02-15 12:59 UTC, Tarotis approved these changes

2023-02-15 12:59 UTC, merged