Add Huisman-2019-110
concepticon/concepticon-data pull request #1328
Opened 2023-07-28 08:56 UTC by mathildavz

# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
  * [ ] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

...

2023-07-28 08:57 UTC, mathildavz commented
The `concepticon test` was passed:
INFO    all integrity tests passed: OK

2023-07-30 13:47 UTC, chrzyki commented
Hey,

thank you very much for preparing this list and the PR. I'd very much like to review this list but I'm still on holiday until August 6th. Could the PR wait until then and I'll do the review immediately on the 7th? Thanks!

2023-07-31 06:34 UTC, AnnikaTjuka commented
@chrzyki, sure! I'll moderate the PR.

2023-08-08 08:13 UTC, chrzyki requested changes
Thanks for preparing this list! First round of small reviews/comments. My knowledge of Japanese is very limited and my suggestions might off, so take with a grain of salt. :)

2023-08-08 08:13 UTC, chrzyki commented on concepticondata/conceptlists/Huisman-2019-110.tsv
> +Huisman-2019-110-109	109	to dry	to dry	乾く	kawaku		1398	DRY
Not sure here, but I don't think its the property but rather the action of 'becoming dry', e.g. `1786/DRY UP`?

2023-08-08 08:13 UTC, chrzyki commented on concepticondata/conceptlists/Huisman-2019-110.tsv-metadata.json
> +                    {
There's multiple empty columns after the `CONCEPTICON_GLOSS` row. Ideally these would be removed and the empty column definition removed here.

2023-08-18 08:40 UTC, mathildavz commented
@chrzyki Thank you for fixing the issues with the checks! Is there anything left to do or can this be merged?

2023-08-18 08:46 UTC, chrzyki commented
Not from me, thank you very much again for preparing this list!

2023-08-18 08:46 UTC, chrzyki approved these changes

2023-09-04 10:46 UTC, merged