Added Object Naming List vanDort-2007-50 + TOP (TOY)
concepticon/concepticon-data pull request #1429
Opened 2024-11-21 12:33 UTC by alzkuc

This PR includes the standard set of files required for the addition of a new list to Concepticon. Additionally, it introduces a new concept set: 3996 TOP (TOY), which does not appear in any existing lists but is present in several others that will follow.

# Pull request checklist

- [x] add new concept list
- [x] add new metadata
- [x] add new Concepticon concept sets
  * [x] checked whether the new concept(s) can be applied to existing lists with
    `concepticon notlinked --gloss "NEW_GLOSS"`
- [ ] add new Concepticon concept relations
- [ ] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information

...

2024-11-21 12:55 UTC, LinguList commented
@Risious, having done some work on concepticon, could you check these mappings quickly? I will then also double check. In this way, we learn already the review process. @alzkuc, if Riccardo does not see this, can you communicate with him directly, as I may not be that much online tomorrow.

2024-11-21 13:07 UTC, alzkuc commented
> @Risious, having done some work on concepticon, could you check these mappings quickly? I will then also double check. In this way, we learn already the review process. @alzkuc, if Riccardo does not see this, can you communicate with him directly, as I may not be that much online tomorrow.

of course!

2024-11-22 08:35 UTC, Risious requested changes
looks good, i found a typo in the concept list line 45 :)

2024-11-22 08:35 UTC, Risious commented on concepticondata/conceptlists/vanDort-2007-50.tsv
> +vanDort-2007-50-44	44	Funnel	Corong/Copofng/ Calong	2602	FUNNEL
there is a typo in this line, Corong/Copofng/ Calong -> Corong/Copong/Calong

2024-11-22 10:20 UTC, merged