relate to #918
concepticon/concepticon-data pull request #920
Opened 2020-08-31 08:58 UTC by MacyL

# Pull request checklist

- [ ] add new concept list
- [ ] add new metadata
- [ ] add new Concepticon concept sets
- [ ] add new Concepticon concept relations
- [x] refine existing Concepticon concept set mappings
- [ ] refine Concepticon glosses
- [ ] refine Concepticon concept relations
- [ ] refine Concepticon concept definitions
- [ ] retire data

## Additional information
relate to issue #918 
...

2020-08-31 09:27 UTC, LinguList requested changes

2020-08-31 09:27 UTC, LinguList commented on concepticondata/conceptlists/BeijingDaxue-1964-905.tsv
> +BeijingDaxue-1964-905-527	527	舉	264	verb	body-part related actions	三、肢體動作	動詞	raise (something with hand)	jǔ	1317	RAISE	举
We had long discussions about this. @MacyL, can you ask @Schweikhard to double check?

2020-08-31 09:27 UTC, LinguList commented on concepticondata/conceptlists/BeijingDaxue-1964-905.tsv
> +BeijingDaxue-1964-905-611	611	闲谈	306	verb	communication	五、交際、事務、人事	動詞	talk, make smalltalk	xián tán	2903	CHAT (WITH SOMEBODY)	闲谈
@MacyL, you realized we use long and short characters in teh two columns, right? I assume that the first character should then be 閒談, right?

2020-08-31 11:29 UTC, MacyL commented on concepticondata/conceptlists/BeijingDaxue-1964-905.tsv
> +BeijingDaxue-1964-905-527	527	舉	264	verb	body-part related actions	三、肢體動作	動詞	raise (something with hand)	jǔ	1317	RAISE	举
wait, I didn't change this row. I pulled the data from the Master branch, and then change the 闲谈 characters and mappings. I have no idea why this is different. But thanks for this one, I will make another issue about what I have found.

2020-08-31 11:50 UTC, MacyL commented on concepticondata/conceptlists/BeijingDaxue-1964-905.tsv
> +BeijingDaxue-1964-905-611	611	闲谈	306	verb	communication	五、交際、事務、人事	動詞	talk, make smalltalk	xián tán	2903	CHAT (WITH SOMEBODY)	闲谈
ah true, sorry for not noticing it. The column was "Chinese" and "Chinese simplified". So I was a bit confused the column meaning. I will change it now.

2020-08-31 13:02 UTC, LinguList commented
I think, @MacyL, you can add the revisions proposed in #921 here, then we have all in one place. Otherwise, you have to also modify the RAISE. And I'd suggest @Schweikhard as another reviewer.

2020-09-14 17:23 UTC, LinguList commented
@MacyL, did you follow up on my comment from 14 days ago? I don't see any changes. You should inform me, if you made them, as I am not always notified of this. This PR has been open for too long a time...

2020-09-17 07:55 UTC, MacyL commented
Somehow this comments didn't send to my mailbox, sorry. I will do so.

2020-09-17 08:45 UTC, Schweikhard requested changes

2020-09-17 08:45 UTC, Schweikhard commented on concepticondata/conceptlists/BeijingDaxue-1964-905.tsv
> +BeijingDaxue-1964-905-527	527	舉	264	verb	body-part related actions	三、肢體動作	動詞	raise (something with hand)	jǔ	1317	RAISE	举
I wasn't sure whether my input is needed here as this seemed to have been an unintentional change. As the PR is being discussed again - what is the difference in meaning between RAISE and LIFT?
RAISE includes 舉 and 举(~手), whereas 提, 举起, 揭(~盖子), 抬, 揭（盖子） and 举起, as well as raise, lift and some mismappings referring to raising a child or animal (including 养（养鸡）).

So I would guess that LIFT is about taking an object and increasing its altitude, whereas RAISE is about increasing the altitude of a body part like one's arm or hand.

If that's accurate, then this raise (something with hand) here should be changed back to LIFT (and the raise = bring up mappings fixed) and the definitions should be made clearer.

2020-09-17 08:48 UTC, Schweikhard commented on concepticondata/conceptlists/BeijingDaxue-1964-905.tsv
> +BeijingDaxue-1964-905-527	527	舉	264	verb	body-part related actions	三、肢體動作	動詞	raise (something with hand)	jǔ	1317	RAISE	举
If of course both mean "taking an object and increasing its altitude" (as the English translation here would imply), then everything at RAISE should be moved to LIFT and RAISE be retired.

2020-09-17 08:49 UTC, MacyL commented on concepticondata/conceptlists/BeijingDaxue-1964-905.tsv
> +BeijingDaxue-1964-905-527	527	舉	264	verb	body-part related actions	三、肢體動作	動詞	raise (something with hand)	jǔ	1317	RAISE	举
I agree that the RAISE should be body part related, and lift is to increase an object's altitude. However, I believe that BeijingDaxue's 舉 is body part related movement, so it should be mapped to RAISE according to the above two conditions? No?

2020-09-17 08:56 UTC, Schweikhard commented on concepticondata/conceptlists/BeijingDaxue-1964-905.tsv
> +BeijingDaxue-1964-905-527	527	舉	264	verb	body-part related actions	三、肢體動作	動詞	raise (something with hand)	jǔ	1317	RAISE	举
So the English translation is unreliable?

2020-09-17 09:01 UTC, MacyL commented on concepticondata/conceptlists/BeijingDaxue-1964-905.tsv
> +BeijingDaxue-1964-905-527	527	舉	264	verb	body-part related actions	三、肢體動作	動詞	raise (something with hand)	jǔ	1317	RAISE	举
I can't say that the English translation is unreliable, but I personally believe that 提 is more suitable to map to LIFT than 舉 (both were mapped to LIFT).

2020-09-17 09:36 UTC, LinguList commented on concepticondata/conceptlists/BeijingDaxue-1964-905.tsv
> +BeijingDaxue-1964-905-527	527	舉	264	verb	body-part related actions	三、肢體動作	動詞	raise (something with hand)	jǔ	1317	RAISE	举
On what grounds, @MacyL, did you check the dialect readings? The English translation was added by myself, using an automated procedure. The Chinese reading is the important one, so if you have better translations, please also modify those.

2020-09-17 10:01 UTC, laiyunfan commented
I think:
提: The action increases the altitude of an object, **with the arm naturally positioned hung down**
舉（举）: The action increases the altitude of an object **to somewhere equal to higher than the head**. For example, weight-lifting is translated as 舉重（舉-weight）.

It is for me impossible to fit it in any of the English concepts, or do you have better suggestions after reading my interpretation?

2020-09-17 10:07 UTC, LinguList commented
Thanks, @laiyunfan. I suggest, we do not need to link BOTH concepts, but could link 舉（举）to "lift", as this involves the hand?

2020-09-17 10:38 UTC, MacyL commented
At this point, I ask for a clear instruction on how should I map these concepts.
1. what about the 提 in this concept? Unmap or keep the LIFT
2. what about the concepts in the issue #921 

if we now change this 舉  back to LIFT, then the issue #921 has no significant improvement. Because the mapping in LIFT includes 舉 提 揭 養。 what I am doing is that these single words does not have a clear English meaning or translation, so I was moving all the 舉 to RAISE, and 提 to LIFT as a way to regulate the Chinese concept mapping.  That's my argument of making these changes, but I am not a concepticon expert, so I need a clear instruction on how should I map these concepts

2020-09-17 11:06 UTC, LinguList commented
@Macyl, if there is no clear counterpart, and another translation seems
to be needed, then you should use a different translation and make a new
concepticon concept set.

2020-09-17 11:08 UTC, LinguList commented
So what I suppose is then: let us first get back to the original issue and not modify things here. So we leave the lift parts unmapped, but you can correct the other aspect in your modification to Beijing Daxue. Then, when a decision was reached at in the issue, you can make a new issue. And we ask @laiyunfan to help by finding good glosses, if you consider both words not being covered in their basic meaning by any existing conceptticon concept sett.

2020-09-17 11:10 UTC, LinguList reviewed
Please see my comments, @macyl, it seems we may need a "lift over head" concept set. But we want to discuss this in the issue before, not making a half-cooked PR now here. So if you revert those changes, where I indicated, we can merge this PR and pursue the discussion later in the issue, okay?

2020-09-17 11:10 UTC, LinguList commented on concepticondata/conceptlists/Castro-2010-540.tsv
> +Castro-2010-540-412	412	to lift (over head)	举起	1317	RAISE
Leave this as it was.

2020-09-17 11:10 UTC, LinguList commented on concepticondata/conceptlists/Sun-1991-1004.tsv
> +Sun-1991-1004-592			592	抬	carry on a pole (two people)
Leave this as it was.

2020-09-17 11:10 UTC, LinguList commented on concepticondata/conceptlists/Yang-2011-1014.tsv
> +Yang-2011-1014-564	564	559	lift (over head)	举起	559	lift (over head)	1317	RAISE
leave this as was or unlink

2020-09-17 12:52 UTC, MacyL commented
I have made the changes accordingly. Please have a look

2020-09-17 13:03 UTC, LinguList approved these changes

2020-09-17 13:04 UTC, LinguList commented
@Schweikhard or @laiyunfan, can you approve, so we can merge?

2020-09-17 14:21 UTC, laiyunfan approved these changes

2020-09-17 14:57 UTC, Schweikhard approved these changes

2020-09-17 15:12 UTC, merged